### ISSUE TITLE
[DASHBOARD] Story 2.1. Я, как администратор, хочу иметь возможность авторизации  для управления порталом.

### ISSUE THREAD

**Issue by danilchican** [danilchican/diploma-fksis#1]
- [ ] Task 2.1-1 Страница авторизации. #34 
- [ ] Task 2.1-2 Обработка формы авторизации. #35 
- [ ] Task 2.1-3 Обработка и вывод ошибок. #36
