### ISSUE TITLE
[DASHBOARD] Story 2.8. Я, как администратор, хочу иметь возможность выйти из профиля портала, чтобы никто не мог получить несанкционированный доступ к моему аккаунту.

### ISSUE THREAD

**Issue by danilchican** [danilchican/diploma-fksis#14]
- [x] Task 2.8-1 Выход из аккаунта. #48
- [x] Task 2.8-2 Обработка запроса на выход. #49
- [x] Task 2.8-3 Валидация запроса на выход. #50
