### ISSUE TITLE
[DASHBOARD] Story 2.9. Я, как администратор, хочу иметь возможность управлять новостями на портале.

### ISSUE THREAD

**Issue by danilchican** [danilchican/diploma-fksis#15]
- [x] Task 2.9-1 Страница создания новости. #51
- [x] Task 2.9-2 Страница редактирования новости. #52
- [x] Task 2.9-3 Удаление новости. #53
- [x] Task 2.9-4 Валидация при удалении новости. #54 
- [x] Task 2.9-5 Подгрузка данных при редактировании новости. #55
- [x] Task 2.9-6 Обработка формы обновления новости. #56
- [x] Task 2.9-7 Валидация при обновлении новости. #57
- [x] Task 2.9-8 Валидация при создании новости. #58
- [x] Task 2.9-9 Обработка формы создания новости. #59
- [x] Task 2.9-10 Страница со списком новостей. #70
