### ISSUE TITLE
[DASHBOARD] Story 2.10. Я, как администратор, хочу иметь возможность размещать актуальные объявления на портале.

### ISSUE THREAD

**Issue by danilchican** [danilchican/diploma-fksis#16]
- [x] Task 2.10-1 Страница создания объявления. #60
- [x] Task 2.10-2 Страница редактирования объявления. #61
- [x] Task 2.10-3 Удаление объявления. #62 
- [x] Task 2.10-4 Валидация при удалении объявления. #63 
- [x] Task 2.10-5 Подгрузка данных при редактировании объявления. #64 
- [x] Task 2.10-6 Обработка формы обновления объявления. #65 
- [x] Task 2.10-7 Валидация при обновлении объявления. #66 
- [x] Task 2.10-8 Валидация при создании объявления. #67 
- [x] Task 2.10-9 Обработка формы создания объявления. #68 
- [x] Task 2.10-10 Страница со списком объявлений. #69
