### ISSUE TITLE
[DASHBOARD] Story 2.12. Я, как администратор, хочу иметь возможность размещать информационные страницы.

### ISSUE THREAD

**Issue by danilchican** [danilchican/diploma-fksis#18]
- [x] Task 2.12-1 Страница создания информационной страницы. #71
- [x] Task 2.12-2 Страница редактирования информационной страницы. #72
- [x] Task 2.12-3 Удаление информационной страницы. #73
- [x] Task 2.12-4 Валидация при удалении информационной страницы. #74 
- [x] Task 2.12-5 Подгрузка данных при редактировании информационной страницы. #75
- [x] Task 2.12-6 Обработка формы обновления информационной страницы. #76
- [x] Task 2.12-7 Валидация при обновлении информационной страницы. #77
- [x] Task 2.12-8 Валидация при создании информационной страницы. #78
- [x] Task 2.12-9 Обработка формы создания информационной страницы. #79
- [x] Task 2.12-10 Страница со списком информационных страниц. #80
