### ISSUE TITLE
[DASHBOARD] Story 2.13. Я, как администратор, хочу иметь возможность управления фотогалереей.

### ISSUE THREAD

**Issue by danilchican** [danilchican/diploma-fksis#19]
- [x] Task 2.13-1 Страница создания фотоальбома. #81
- [x] Task 2.13-2 Страница редактирования фотоальбома. #82
- [x] Task 2.13-3 Страница со списком фотоальбомов. #83 
- [x] Task 2.13-4 Удаление информационной страницы. #84
- [x] Task 2.13-5 Валидация при удалении фотоальбома. #85 
- [x] Task 2.13-6 Подгрузка данных при редактировании фотоальбома. #86
- [x] Task 2.13-7 Обработка формы обновления фотоальбома. #87
- [x] Task 2.13-8 Валидация при обновлении фотоальбома. #88
- [x] Task 2.13-9 Валидация при создании фотоальбома. #89
- [x] Task 2.13-10 Обработка формы создания фотоальбома. #90
