### ISSUE TITLE
[DASHBOARD] Story 2.14. Я, как администратор, хочу иметь возможность управлять тэгами, которые будут предоставлять быстрый поиск по ресурсам.

### ISSUE THREAD

**Issue by danilchican** [danilchican/diploma-fksis#20]
- [ ] Task 2.14-1 Страница создания тэга. #91
- [ ] Task 2.14-2 Страница редактирования тэга. #92
- [ ] Task 2.14-3 Удаление тэга. #93
- [ ] Task 2.14-4 Валидация при удалении тэга. #94 
- [ ] Task 2.14-5 Подгрузка данных при редактировании тэга. #95
- [ ] Task 2.14-6 Обработка формы обновления тэга. #96
- [ ] Task 2.14-7 Валидация при обновлении тэга. #97
- [ ] Task 2.14-8 Валидация при создании тэга. #98
- [ ] Task 2.14-9 Обработка формы создания тэга. #99
- [ ] Task 2.14-10 Страница со списком тэгов. #100
