### ISSUE TITLE
[DASHBOARD] Story 2.2. Я, как администратор, хочу иметь возможность восстановить пароль от аккаунта на портале по электронной почте.

### ISSUE THREAD

**Issue by danilchican** [danilchican/diploma-fksis#3]
- [ ] Task 2.2-1 Страница для восстановления пароля. #37
- [ ] Task 2.2-2 Обработка формы. #38
- [ ] Task 2.2-3 Валидация данных. #39
